### ISSUE TITLE
Load Workspace Error

### ISSUE THREAD

**Issue by ewholling** [saralinker/brainImageR#1]
Unable to access the expression hub of ABA data when initially trying to load the workspace through the workspaceload() command. Looks like the command file has been updated recently, as it includes suppression of warnings that appear in the below error message. 

```
> brainImageR:::loadworkspace()
snapshotDate(): 2018-04-27
Error in hub[["EH1434"]] : unknown key ‘EH1434’
```

**Comment by saralinker** [comment]
Hi @ewholling sorry for the delay. 

BrainImageR was optimized for the most recent version of biocondutor (v3.8). https://bioconductor.org/packages/devel/bioc/html/BiocInstaller.html

Please try installing this version and re-run the loadworkspace function.

**Comment by saralinker** [comment]
Hi @ewholling, 

Just checking in. Was installation of the dev release of bioconductor able to fix your issue? If so, I'll go ahead and close this issue. 

Best,
Sara

**Comment by ewholling** [comment]
Yes, thanks so much Sara. You can close the issue.

Ethan
